'use client';
import Link from 'next/link';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      {/* Hero Section */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-6">
            Transform Your Learning with AI
          </h1>
          <p className="mt-3 text-xl text-gray-600 max-w-2xl mx-auto">
            LearnGenius creates personalized study plans tailored to your 
            <span className="text-indigo-600 font-medium"> learning style</span>, 
            <span className="text-indigo-600 font-medium"> age</span>, and 
            <span className="text-indigo-600 font-medium"> subject</span> needs.
          </p>
        </div>

        {/* Key Features Grid */}
        <div className="mt-16 grid gap-8 md:grid-cols-3">
          {[
            {
              title: "AI-Powered Plans",
              desc: "Get customized explanations generated by Groq's LLaMA 3 AI",
              icon: "🤖"
            },
            {
              title: "Style Matching",
              desc: "Optimized for visual, auditory, and kinesthetic learners",
              icon: "🎨"
            },
            {
              title: "Instant Results",
              desc: "Generate complete learning plans in under 5 seconds",
              icon: "⚡"
            }
          ].map((feature, i) => (
            <div key={i} className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow">
              <div className="text-4xl mb-4">{feature.icon}</div>
              <h3 className="text-lg font-semibold text-gray-900">{feature.title}</h3>
              <p className="mt-2 text-gray-600">{feature.desc}</p>
            </div>
          ))}
        </div>

        {/* CTA Button */}
        <div className="mt-12 text-center">
          <Link 
            href="/planner/input"
            className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 transition-colors"
          >
            Start Planning Now →
          </Link>
        </div>
      </main>
    </div>
  );
}